services:
  app-node:
    # O ponto (.) diz para o Docker buscar o "Dockerfile" nesta mesma pasta
    build: .
    
    # Nome que aparecerá quando você der "docker ps" no servidor
    container_name: node_teste_api
    
    # Faz o container subir sozinho se o servidor reiniciar ou o app cair
    restart: always
    
    ports:
      # Formato: [Porta do Servidor]:[Porta do Container]
      # A porta 3000 do seu servidor apontará para a 3000 do Node
      - "3000:3000"
    
    # Define variáveis de ambiente se precisar (opcional)
    environment:
      - NODE_ENV=production
