name: Deploy

on:
  push:
    # Dispara o deploy tanto na main quanto na develop
    branches: [ "main", "develop" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}       # IP do servidor nos Secrets
          username: deploy                   # Usuário com permissão Docker
          key: ${{ secrets.VPS_SSH_KEY }}     # Conteúdo da sua id_rsa
          script: |
            mkdir -p /home/deploy/apps/app
            cd /home/deploy/apps/app

            if [ ! -d ".git" ]; then
              # Tente clonar via HTTPS (se for público) ou SSH
              git clone https://github.com/arruda384/aula-devops.git .
            else
              git pull --ff-only
            fi

            # Comando de diagnóstico: lista os arquivos para vermos se o docker-compose.yml está lá
            ls -la

            # O comando do docker agora apontando explicitamente para o arquivo se necessário
            docker compose up -d --build

            docker compose down
            docker compose up -d --build
